version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  authservice:
    build:
      context: ./backend/authservice
      dockerfile: Dockerfile
    ports:
      - "${AUTHSERVICE_PORT}:${AUTHSERVICE_PORT}"
    env_file:
      - .env

  publicdataservice:
    build:
      context: ./backend/publicdataservice
      dockerfile: Dockerfile
    ports:
      - "${PUBLICDATA_PORT}:${PUBLICDATA_PORT}"
    env_file:
      - .env

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
