# Use the official Node.js image as base
FROM node:14

# Set the working directory in the container
WORKDIR /

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install cors
RUN npm install axios
RUN npm install dotenv

# Copy the rest of the application files to the working directory
COPY . .

# Expose the port on which the application will run
EXPOSE 3001

# Command to run the application
CMD ["node", "src/app.js"]
